---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "memcached-${MOLECULE_SCENARIO_NAME}"
    image: "${DOCKER_REGISTRY:-quay.io/gotmax23}/${DOCKER_IMAGE_TAG:-debian-systemd:trixie}"
    command: ${DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    systemd: true
    groups:
      - memcached

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../../tests/prepare.yml
    converge: ../../tests/test.yml
    verify: ../../tests/verify.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: default
